package nowsh

var CountryCode map[string]string

func init() {
	// Initials of countries names in API Nowsh
	CountryCode = map[string]string{
		"AU": "Australia",
		"AT": "Austria",
		"CA": "Canada",
		"CN": "China",
		"DK": "Denmark",
		"FI": "Finland",
		"FR": "France",
		"DE": "Germany",
		"IS": "Iceland",
		"IE": "Ireland",
		"IT": "Italy",
		"NL": "Netherlands",
		"NO": "Norway",
		"SE": "Sweden",
		"CH": "Switzerland",
		"GB": "United Kingdom",
		"ES": "Spain",
		"MX": "Mexico",
		"CL": "Chile",
		"BR": "Brazil",
		"AF": "Afghanistan",
		"AL": "Albania",
		"DZ": "Algeria",
		"AD": "Andorra",
		"AO": "Angola",
		"AG": "Antigua and Barbuda",
		"AR": "Argentina",
		"AM": "Armenia",
		"AZ": "Azerbaijan",
		"BS": "Bahamas",
		"BH": "Bahrain",
		"BD": "Bangladesh",
		"BB": "Barbados",
		"BY": "Belarus",
		"BE": "Belgium",
		"BZ": "Belize",
		"BJ": "Benin",
		"BT": "Bhutan",
		"BO": "Bolivia",
		"BA": "Bosnia and Herzegovina",
		"BW": "Botswana",
		"BN": "Brunei",
		"BG": "Bulgaria",
		"BF": "Burkina Faso",
		"BU": "Burma",
		"BI": "Burundi",
		"CV": "Cabo Verde",
		"KH": "Cambodia",
		"CM": "Cameroon",
		"CF": "Central African Republic",
		"TD": "Chad",
		"CO": "Colombia",
		"KM": "Comoros",
		"CG": "Congo (Brazzaville)",
		"CD": "Congo (Kinshasa)",
		"CR": "Costa Rica",
		"CI": "Cote d'Ivoire",
		"HR": "Croatia",
		"CU": "Cuba",
		"CY": "Cyprus",
		"CZ": "Czechia",
		"DJ": "Djibouti",
		"DM": "Dominica",
		"DO": "Dominican Republic",
		"EC": "Ecuador",
		"EG": "Egypt",
		"SV": "El Salvador",
		"GQ": "Equatorial Guinea",
		"ER": "Eritrea",
		"EE": "Estonia",
		"SZ": "Eswatini",
		"ET": "Ethiopia",
		"FJ": "Fiji",
		"GA": "Gabon",
		"GM": "Gambia",
		"GE": "Georgia",
		"GH": "Ghana",
		"GR": "Greece",
		"GD": "Grenada",
		"GT": "Guatemala",
		"GN": "Guinea",
		"GW": "Guinea-Bissau",
		"GY": "Guyana",
		"HT": "Haiti",
		"VA": "Holy See",
		"HN": "Honduras",
		"HU": "Hungary",
		"IN": "India",
		"ID": "Indonesia",
		"IR": "Iran",
		"IQ": "Iraq",
		"IL": "Israel",
		"JM": "Jamaica",
		"JP": "Japan",
		"JO": "Jordan",
		"KZ": "Kazakhstan",
		"KE": "Kenya",
		"KR": "Korea, South",
		"XK": "Kosovo",
		"KW": "Kuwait",
		"KG": "Kyrgyzstan",
		"LA": "Laos",
		"LV": "Latvia",
		"LB": "Lebanon",
		"LS": "Lesotho",
		"LR": "Liberia",
		"LY": "Libya",
		"LI": "Liechtenstein",
		"LT": "Lithuania",
		"LU": "Luxembourg",
		"MG": "Madagascar",
		"MW": "Malawi",
		"MY": "Malaysia",
		"MV": "Maldives",
		"ML": "Mali",
		"MT": "Malta",
		"MR": "Mauritania",
		"MU": "Mauritius",
		"MD": "Moldova",
		"MC": "Monaco",
		"MN": "Mongolia",
		"ME": "Montenegro",
		"MA": "Morocco",
		"MZ": "Mozambique",
		"NA": "Namibia",
		"NP": "Nepal",
		"NZ": "New Zealand",
		"NI": "Nicaragua",
		"NE": "Niger",
		"NG": "Nigeria",
		"MK": "North Macedonia",
		"OM": "Oman",
		"PK": "Pakistan",
		"PA": "Panama",
		"PG": "Papua New Guinea",
		"PY": "Paraguay",
		"PE": "Peru",
		"PH": "Philippines",
		"PL": "Poland",
		"PT": "Portugal",
		"QA": "Qatar",
		"RO": "Romania",
		"RU": "Russia",
		"RW": "Rwanda",
		"KN": "Saint Kitts and Nevis",
		"LC": "Saint Lucia",
		"VC": "Saint Vincent and the Grenadines",
		"SM": "San Marino",
		"ST": "Sao Tome and Principe",
		"SA": "Saudi Arabia",
		"SN": "Senegal",
		"RS": "Serbia",
		"SC": "Seychelles",
		"SL": "Sierra Leone",
		"SG": "Singapore",
		"SK": "Slovakia",
		"SI": "Slovenia",
		"SO": "Somalia",
		"ZA": "South Africa",
		"SS": "South Sudan",
		"LK": "Sri Lanka",
		"SD": "Sudan",
		"SR": "Suriname",
		"SY": "Syria",
		"TW": "Taiwan*",
		"TJ": "Tajikistan",
		"TZ": "Tanzania",
		"TH": "Thailand",
		"TL": "Timor-Leste",
		"TG": "Togo",
		"TT": "Trinidad and Tobago",
		"TN": "Tunisia",
		"TR": "Turkey",
		"UG": "Uganda",
		"UA": "Ukraine",
		"AE": "United Arab Emirates",
		"UY": "Uruguay",
		"US": "US",
		"UZ": "Uzbekistan",
		"PS": "West Bank and Gaza",
		"EH": "Western Sahara",
		"YE": "Yemen",
		"ZM": "Zambia",
		"ZW": "Zimbabwe",
	}
}
