package providers

import "context"

var providers []Provider

// Data generated by generic provider
type Data struct {
	Confirmed, Deaths, Recovered int
	Error                        error
	Provider                     string
	Country                      string
}

// Provider interface
type Provider interface {
	Request(ctx context.Context)
	Wait()
	Response() []Data
}

// Register provider
func Register(provider Provider) {
	providers = append(providers, provider)
}

// Providers returns registered providers
func Providers() []Provider {
	return providers
}
